-- MySQL Script generated by MySQL Workbench
-- Wed Dec 27 17:40:04 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `schedule_site` DEFAULT CHARACTER SET utf8 ;
USE `schedule_site` ;

-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_site`.`customers` ;

CREATE TABLE IF NOT EXISTS `schedule_site`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `home_phone` VARCHAR(45) NULL,
  `mobile_phone` VARCHAR(45) NULL,
  `work_phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `address2` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `county_state` VARCHAR(45) NULL,
  `post_zip_code` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  `updated_at` TIMESTAMP NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_site`.`pets` ;

CREATE TABLE IF NOT EXISTS `schedule_site`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `dob` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `is_neutered` VARCHAR(45) NULL,
  `behaviour` VARCHAR(45) NULL,
  `micro_chip` VARCHAR(255) NULL,
  `image_url` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  `updated_at` TIMESTAMP NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id`),
  INDEX `fk_petse_customers_idx` (`customer_id` ASC),
  CONSTRAINT `fk_petse_customers`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_site`.`appointments` ;

CREATE TABLE IF NOT EXISTS `schedule_site`.`appointments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NULL,
  `start_time` TIME NULL,
  `end_date` DATE NULL,
  `end_time` TIME NULL,
  `pet_id` INT NULL,
  `user_id` INT NULL,
  `notes` VARCHAR(255) NULL,
  `status` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  `updated_at` TIMESTAMP NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id`),
  INDEX `fk_schedules_pets_idx` (`pet_id` ASC),
  CONSTRAINT `fk_appointments_pets`
    FOREIGN KEY (`pet_id`)
    REFERENCES `mydb`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_site`.`services` ;

CREATE TABLE IF NOT EXISTS `schedule_site`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` INT NULL,
  `unit_price` FLOAT NULL,
  `quantity` INT NULL,
  `notes` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  `updated_at` TIMESTAMP NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`appointments_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_site`.`appointments_services` ;

CREATE TABLE IF NOT EXISTS `schedule_site`.`appointments_services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `appointment_id` INT NULL,
  `service_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shedules_services_schedule_idx` (`appointment_id` ASC),
  INDEX `fk_shedules_services_services_idx` (`service_id` ASC),
  CONSTRAINT `fk_appointments_services_appointments`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `mydb`.`appointments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointments_services_services`
    FOREIGN KEY (`service_id`)
    REFERENCES `mydb`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_site`.`users` ;

CREATE TABLE IF NOT EXISTS `schedule_site`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `company_name` VARCHAR(255) NULL,
  `country_type` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `remember_token` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  `updated_at` TIMESTAMP NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`settings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `schedule_site`.`settings` ;

CREATE TABLE IF NOT EXISTS `schedule_site`.`settings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `value` LONGTEXT NULL,
  `user_id` INT NULL,
  `created_at` TIMESTAMP NULL DEFAULT now(),
  `updated_at` TIMESTAMP NULL DEFAULT now() ON UPDATE now(),
  PRIMARY KEY (`id`),
  INDEX `fk_settings_users_idx` (`user_id` ASC),
  CONSTRAINT `fk_settings_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
